### ISSUE TITLE
Memcached throws NoMethodError in `clear_cache`

### ISSUE THREAD

**Issue by tramuntanal** [mainio/decidim-module-term_customizer#30]
The method `Decidim::TermCustomizer::Loader#clear_cache` uses the `Rails.cache.delete_matched` method to avoid rebuilding the whole cache when applying translations. https://github.com/mainio/decidim-module-term_customizer/blob/5d7dca16af4f4cb049f1f573f6c5eefd8b427fc0/lib/decidim/term_customizer/loader.rb#L59

But this method is not supported by all cache implementations. Then the `Loader` class controls this situation implementing a `rescue NotImplementedError`. The problem is that Memcached's `dally` adapter raises a `NoMethodError` instead, this causes the application to crash when the user clears term-customizer's cache.

**Comment by victorol1** [comment]
There are a few fixes as mentioned here: https://github.com/refinery/refinerycms/issues/2130#issuecomment-12236630
I implement one of the fixes on this PR: https://github.com/mainio/decidim-module-term_customizer/pull/31

**Comment by ahukkanen** [comment]
Fixed by #31
