### ISSUE TITLE
Version compatibility error with decidim 0.22

### ISSUE THREAD

**Issue by iseimandi** [mainio/decidim-module-term_customizer#42]
Hello, we want to install this module on our decidim platform and when running we get the following error:

Resolving dependencies......
Bundler could not find compatible versions for gem "decidim-core":
  In Gemfile:
    decidim-dev (= 0.22.0) was resolved to 0.22.0, which depends on
      decidim (= 0.22.0) was resolved to 0.22.0, which depends on
        decidim-core (= 0.22.0)
decidim-term_customizer was resolved to 0.16.6, which depends on
  decidim-core (~> 0.16.0)

Our version of decidim is 0.22 and we see in the code of
mainio / decidim-module-term_customizer that says "Update to dependencies of decidim 0.22" but for some reason it takes us a version of the module compatible with decidim 0.16.0

I will appreciate if you can help me install the version of the module compatible with decidim 0.22

We add the following line to the Gemfile file:
gem "decidim-term_customizer"

And then execute:
$ bundle
$ bundle exec rails decidim_term_customizer:install:migrations
$ bundle exec rails db:migrate

**Comment by mrcasals** [comment]
@iseimandi it looks like latest versions haven't been pushed to RubyGems. you'll need to use the code straight from the GitHub repo:

```ruby
# Gemfile

gem 'decidim-term_customizer', git: 'https://github.com/mainio/decidim-module-term_customizer.git'
```

**Comment by iseimandi** [comment]
Thanks a lot @mrcasals! we managed to install the module and make the changes in the texts that we needed.

Cheers!
