### ISSUE TITLE
bundle exec rails decidim_term_customizer:install:migrations fails

### ISSUE THREAD

**Issue by mattstone** [mainio/decidim-module-term_customizer#5]
Hello,

I've just installed the gem, then attempted to install the migrations

This is the output from: bundle exec rails decidim_term_customizer:install:migrations --trace

zen:democracy matt$ bundle exec rails decidim_term_customizer:install:migrations --trace
rails aborted!
Don't know how to build task 'decidim_term_customizer:install:migrations' (See the list of available tasks with `rake --tasks`)
Did you mean?  decidim_verifications:install:migrations
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task_manager.rb:59:in `[]'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:159:in `invoke_task'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/command.rb:48:in `invoke'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<main>'
/Users/matt/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/matt/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/matt/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
/Users/matt/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/matt/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/matt/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'

This is the output from bundle info decidim-term_customizer

zen:democracy matt$ bundle info decidim-term_customizer
  * decidim-term_customizer (0.16.1)
	Summary: Provides possibility to customize Decidim's localized terms.
	Homepage: https://github.com/mainio/decidim-module-term_customizer
	Path: /Users/matt/.rvm/gems/ruby-2.6.1/gems/decidim-term_customizer-0.16.1

I've just copied the migrations from github, then renamed them at it all seems ok.

**Comment by ahukkanen** [comment]
Fixed by 7256d65ec10ce6aa7ccffbc1855371987435c251.
