### ISSUE TITLE
Uninstall instructions in readme

### ISSUE THREAD

**Issue by BigSnicker** [mainio/decidim-module-term_customizer#62]
I'm doing some troubleshooting and want to remove the module to make sure that it's not causing any problems.

Would you be able to put the uninstall process in the readme file, to help new users do it correctly?

**Comment by ahukkanen** [comment]
If you remove the gem from your gemfile and run `bundle`, it won't be doing anything anymore.

It will still leave the database tables behind but they don't matter for debugging if the gem is not doing anything.
