### ISSUE TITLE
Problem after install : can't add a new translation set

### ISSUE THREAD

**Issue by AnthonyFon** [mainio/decidim-module-term_customizer#68]
Hi,

I install the module without problem. I can see "Paramétage des traduction" (french user) in the admin panel but if I click to add a new set of translation, that's going on page which say " error with our server" (link : admin/term_customizer/sets/new)

Can you help me to resolv this ?
Thank's a lot.
Best regards

**Comment by ahukkanen** [comment]
You will need to attach more information in order to debug this further.

At minimum, the following information would help debug further:

- Full stacktrace of the error
- Link to your instances code where we can see what other modules you may have installed

**Comment by AnthonyFon** [comment]
Thank's for your reply.
My Gemfile:

`# frozen_string_literal: true

source "https://rubygems.org"

ruby RUBY_VERSION

gem "decidim", git: "https://github.com/decidim/decidim.git", branch: "release/0.23-stable"
gem "decidim-consultations", git: "https://github.com/decidim/decidim.git", branch: "release/0.23-stable"
gem "decidim-navbar_links", git: "https://github.com/OpenSourcePolitics/decidim-module-navbar_links.git", branch: "0.23-stable"
gem "decidim-term_customizer"
gem "decidim-proposals"

gem "bootsnap", "~> 1.3"

gem "puma", ">= 4.3.5"
gem "uglifier", "~> 4.1"

gem "faker", "~> 1.9"

gem "wicked_pdf", "~> 1.4"

gem "figaro"

group :development, :test do
  gem "byebug", "~> 11.0", platform: :mri

  gem "decidim-dev", "0.23.4"
end

group :development do
  gem "letter_opener_web", "~> 1.3"
  gem "listen", "~> 3.1"
  gem "spring", "~> 2.0"
  gem "spring-watcher-listen", "~> 2.0"
  gem "web-console", "~> 3.5"
end
group :production do
  gem "passenger"
  gem 'delayed_job_active_record'
  gem "daemons"
end
`
I put what I see in production.log :
D, [2021-04-23T16:52:21.186791 #13033] DEBUG -- : [2df3cc32-fbbd-4bb6-a439-c6137077f51b]   [1m[36mCACHE Decidim::Assembly Exists (0.0ms)[0m  [1m[34mSELECT  1 AS one FROM "decidim_assemblies" WHERE "decidim_assemblies"."decidim_organization_id" = $1 LIMIT $2[0m  [["decidim_organization_id", 1], ["LIMIT", 1]]
I, [2021-04-23T16:52:21.193004 #13033]  INFO -- : [2df3cc32-fbbd-4bb6-a439-c6137077f51b]   Rendered /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/decidim-ce79b790bb75/decidim-admin/app/views/layouts/decidim/admin/_template_bottom.html.erb (0.1ms)
I, [2021-04-23T16:52:21.195119 #13033]  INFO -- : [2df3cc32-fbbd-4bb6-a439-c6137077f51b]   Rendered /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/decidim-ce79b790bb75/decidim-core/app/views/decidim/shared/_confirm_modal.html.erb (1.4ms)
I, [2021-04-23T16:52:21.195335 #13033]  INFO -- : [2df3cc32-fbbd-4bb6-a439-c6137077f51b]   Rendered /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/decidim-ce79b790bb75/decidim-admin/app/views/layouts/decidim/admin/_application.html.erb (34.4ms)
I, [2021-04-23T16:52:21.196273 #13033]  INFO -- : [2df3cc32-fbbd-4bb6-a439-c6137077f51b] Completed 200 OK in 83ms (Views: 69.7ms | ActiveRecord: 10.4ms)
I, [2021-04-23T16:52:22.745974 #13033]  INFO -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1] Started GET "/admin/term_customizer/sets/new" for 86.254.229.115 at 2021-04-23 16:52:22 +0200
D, [2021-04-23T16:52:22.748873 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mDecidim::Organization Load (1.0ms)[0m  [1m[34mSELECT  "decidim_organizations".* FROM "decidim_organizations" WHERE "decidim_organizations"."host" = $1 LIMIT $2[0m  [["host", "jeparticipe.soyaux.fr"], ["LIMIT", 1]]
D, [2021-04-23T16:52:22.757919 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mDecidim::User Load (1.4ms)[0m  [1m[34mSELECT  "decidim_users".* FROM "decidim_users" WHERE "decidim_users"."type" IN ('Decidim::User') AND "decidim_users"."id" = $1 ORDER BY "decidim_users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
D, [2021-04-23T16:52:22.761363 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mCACHE Decidim::User Load (0.0ms)[0m  [1m[34mSELECT  "decidim_users".* FROM "decidim_users" WHERE "decidim_users"."type" IN ('Decidim::User') AND "decidim_users"."id" = $1 ORDER BY "decidim_users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
D, [2021-04-23T16:52:22.764866 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mDecidim::Organization Load (1.1ms)[0m  [1m[34mSELECT  "decidim_organizations".* FROM "decidim_organizations" WHERE "decidim_organizations"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
I, [2021-04-23T16:52:22.769747 #13033]  INFO -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1] Processing by Decidim::TermCustomizer::Admin::TranslationSetsController#new as HTML
I, [2021-04-23T16:52:22.811766 #13033]  INFO -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   Rendering /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/decidim-term_customizer-0.23.0/app/views/decidim/term_customizer/admin/translation_sets/new.html.erb within layouts/decidim/admin/application
D, [2021-04-23T16:52:22.839880 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mDecidim::ParticipatoryProcess Load (1.0ms)[0m  [1m[34mSELECT "decidim_participatory_processes".* FROM "decidim_participatory_processes" WHERE "decidim_participatory_processes"."decidim_organization_id" = $1[0m  [["decidim_organization_id", 1]]
D, [2021-04-23T16:52:22.844162 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mDecidim::Assembly Load (1.6ms)[0m  [1m[34mSELECT "decidim_assemblies".* FROM "decidim_assemblies" WHERE "decidim_assemblies"."decidim_organization_id" = $1[0m  [["decidim_organization_id", 1]]
D, [2021-04-23T16:52:22.999739 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mDecidim::Consultation Load (1.2ms)[0m  [1m[34mSELECT "decidim_consultations".* FROM "decidim_consultations" WHERE "decidim_consultations"."decidim_organization_id" = $1[0m  [["decidim_organization_id", 1]]
D, [2021-04-23T16:52:23.004109 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mCACHE Decidim::ParticipatoryProcess Load (0.0ms)[0m  [1m[34mSELECT "decidim_participatory_processes".* FROM "decidim_participatory_processes" WHERE "decidim_participatory_processes"."decidim_organization_id" = $1[0m  [["decidim_organization_id", 1]]
D, [2021-04-23T16:52:23.012885 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mDecidim::Component Load (1.5ms)[0m  [1m[34mSELECT "decidim_components".* FROM "decidim_components" WHERE "decidim_components"."participatory_space_id" = $1 AND "decidim_components"."participatory_space_type" = $2 ORDER BY "decidim_components"."weight" ASC, "decidim_components"."manifest_name" ASC[0m  [["participatory_space_id", 1], ["participatory_space_type", "Decidim::ParticipatoryProcess"]]
D, [2021-04-23T16:52:23.042865 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mCACHE Decidim::Assembly Load (0.0ms)[0m  [1m[34mSELECT "decidim_assemblies".* FROM "decidim_assemblies" WHERE "decidim_assemblies"."decidim_organization_id" = $1[0m  [["decidim_organization_id", 1]]
D, [2021-04-23T16:52:23.047639 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mDecidim::Component Load (0.8ms)[0m  [1m[34mSELECT "decidim_components".* FROM "decidim_components" WHERE "decidim_components"."participatory_space_id" = $1 AND "decidim_components"."participatory_space_type" = $2 ORDER BY "decidim_components"."weight" ASC, "decidim_components"."manifest_name" ASC[0m  [["participatory_space_id", 1], ["participatory_space_type", "Decidim::Assembly"]]
I, [2021-04-23T16:52:23.049497 #13033]  INFO -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   Rendered /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/decidim-term_customizer-0.23.0/app/views/decidim/term_customizer/admin/translation_sets/_constraint_fields.html.erb (217.3ms)
D, [2021-04-23T16:52:23.053502 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mCACHE Decidim::ParticipatoryProcess Load (0.1ms)[0m  [1m[34mSELECT "decidim_participatory_processes".* FROM "decidim_participatory_processes" WHERE "decidim_participatory_processes"."decidim_organization_id" = $1[0m  [["decidim_organization_id", 1]]
D, [2021-04-23T16:52:23.057316 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mCACHE Decidim::Component Load (0.0ms)[0m  [1m[34mSELECT "decidim_components".* FROM "decidim_components" WHERE "decidim_components"."participatory_space_id" = $1 AND "decidim_components"."participatory_space_type" = $2 ORDER BY "decidim_components"."weight" ASC, "decidim_components"."manifest_name" ASC[0m  [["participatory_space_id", 1], ["participatory_space_type", "Decidim::ParticipatoryProcess"]]
D, [2021-04-23T16:52:23.062789 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mCACHE Decidim::Assembly Load (0.0ms)[0m  [1m[34mSELECT "decidim_assemblies".* FROM "decidim_assemblies" WHERE "decidim_assemblies"."decidim_organization_id" = $1[0m  [["decidim_organization_id", 1]]
D, [2021-04-23T16:52:23.066354 #13033] DEBUG -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   [1m[36mCACHE Decidim::Component Load (0.0ms)[0m  [1m[34mSELECT "decidim_components".* FROM "decidim_components" WHERE "decidim_components"."participatory_space_id" = $1 AND "decidim_components"."participatory_space_type" = $2 ORDER BY "decidim_components"."weight" ASC, "decidim_components"."manifest_name" ASC[0m  [["participatory_space_id", 1], ["participatory_space_type", "Decidim::Assembly"]]
I, [2021-04-23T16:52:23.068633 #13033]  INFO -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   Rendered /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/decidim-term_customizer-0.23.0/app/views/decidim/term_customizer/admin/translation_sets/_constraint_fields.html.erb (18.6ms)
I, [2021-04-23T16:52:23.069114 #13033]  INFO -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   Rendered /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/decidim-term_customizer-0.23.0/app/views/decidim/term_customizer/admin/translation_sets/_form.html.erb (249.3ms)
I, [2021-04-23T16:52:23.073217 #13033]  INFO -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   Rendered /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/decidim-term_customizer-0.23.0/app/views/decidim/term_customizer/admin/translation_sets/new.html.erb within layouts/decidim/admin/application (261.2ms)
I, [2021-04-23T16:52:23.074044 #13033]  INFO -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1] Completed 500 Internal Server Error in 304ms (ActiveRecord: 27.8ms)
F, [2021-04-23T16:52:23.078197 #13033] FATAL -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   
F, [2021-04-23T16:52:23.078337 #13033] FATAL -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1] ActionView::Template::Error (The asset "decidim/term_customizer/admin/translation_sets_admin.js" is not present in the asset pipeline.
):
F, [2021-04-23T16:52:23.078499 #13033] FATAL -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]     6:   </div>
[d57ebec3-893f-44fd-99ec-08f07f8adfd1]     7: <% end %>
[d57ebec3-893f-44fd-99ec-08f07f8adfd1]     8: 
[d57ebec3-893f-44fd-99ec-08f07f8adfd1]     9: <%= javascript_include_tag "decidim/term_customizer/admin/translation_sets_admin" %>
F, [2021-04-23T16:52:23.078550 #13033] FATAL -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1]   
F, [2021-04-23T16:52:23.078673 #13033] FATAL -- : [d57ebec3-893f-44fd-99ec-08f07f8adfd1] sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:84:in `compute_asset_path'

Would you like more information ?
Thank's for your help

**Comment by ahukkanen** [comment]
This is not a problem with the module.

Please precompile your assets:
https://guides.rubyonrails.org/asset_pipeline.html#in-production

**Comment by AnthonyFon** [comment]
Working well !
Thank's for your help and your developement !
