### ISSUE TITLE
Update to v0.25

### ISSUE THREAD

**Issue by andreslucena** [mainio/decidim-module-term_customizer#79]
As you know, since version 0.25.0 Decidim uses webpacker for its assets.

@leio10 had already made all the changes for this to work (this was actually in production in Metadecidim for the last couple of months), but I see that he hadn't time to make the PR.

I'm opening this PR just so you're aware of - I'll try to find time next week to make the PR with the cherry-picking myself, but just in case that I couldn't find time or if you prefer to do so yourselves. 

https://github.com/AjuntamentdeBarcelona/decidim-module-term_customizer/tree/feature/webpacker-migration

**Comment by ahukkanen** [comment]
The `develop` branch should work for v0.25.

In case you've found something broken with it, please open the PR against the `develop` branch.

**Comment by andreslucena** [comment]
> The `develop` branch should work for v0.25.

Great! Closing this issue as it was already fixed then
